Интерфейс
Unatart/ChessTravelers pull request #4
Opened 2017-12-06 23:12 UTC by Alexander-Kuznetsov

- добавлено меню
- добавлены разделы (меню, выбор игры, об игре, ввод имени пользователя, статистика игры)
- доблавлена таблица статистики
- добавлена графика
- добавлен основной цикл игры
- доблавлен обработчик событий нажатия кнопки мыши

2017-12-07 06:57 UTC, leshiy1295 requested changes
Когда поправите - оставьте комментарий

2017-12-07 06:57 UTC, leshiy1295 commented on mainwindow.cpp
> +    WHITE = '#',
это должно быть не в mainwindow.cpp - это основное замечание - надо разделить на модули...
в частности, этот enum скорее всего должен быть на уровне модели...

2017-12-07 06:57 UTC, leshiy1295 commented on mainwindow.cpp
> +    size_canvas_width = 400;
магические константы
используйте конфигурационные файлы

2017-12-07 06:57 UTC, leshiy1295 commented on mainwindow.cpp
> +            if (cursor.x() >= j * size_cube_width
а зачем цикл?
разве нельзя определить это остатком от деления?

2017-12-07 06:57 UTC, leshiy1295 commented on mainwindow.cpp
> +void MainWindow::drawCube(QPoint cube, int clr_pen, QColor clr_brush, float percent_offset) {
возможно, имеет смысл использовать один метод с некоторыми параметрами по умолчанию..

2017-12-07 06:57 UTC, leshiy1295 commented on mainwindow.cpp
> +QColor MainWindow::handleColor(int num_clr) {
лучше использовать enum class вместо int...

2017-12-07 06:57 UTC, leshiy1295 commented on mainwindow.cpp
> +    std::string filename = "maps/1.txt";
тут что-то не так
это либо должно читаться из GUI, либо вызываться не здесь и использовать конфигурационные файлы..

2017-12-07 06:57 UTC, leshiy1295 commented on mainwindow.cpp
> +    QSound sound("sound/background.wav");
используйте конфигурацию...

2017-12-07 06:57 UTC, leshiy1295 commented on mainwindow.cpp
> +    exit(1);
а это не приведёт к разного рода утечкам в других модулях?

2017-12-07 06:57 UTC, leshiy1295 commented on mainwindow.cpp
> +void MainWindow::on_Statistic_clicked()
а почему сверху все методы были в CamelCase, а тут - в смешанном стиле?

2017-12-07 06:57 UTC, leshiy1295 commented on mainwindow.h
> +#include <QSound>
возможно, тоже стоит выделить обобщённый интерфейс, который не зависит от Qt, и реализовать одного наследника через Qt...

2017-12-07 06:57 UTC, leshiy1295 commented on mainwindow.h
> +    Ui::MainWindow *ui;
можно заиспользовать умные указатели, чтобы не париться по поводу delete...

2017-12-07 06:57 UTC, leshiy1295 commented on mainwindow.cpp
> +QPoint MainWindow::ConvertToQPoint(Coordinates coord) {
вот этот слой по идее не должен быть в модуле рисования - возможно, это должен быть какой-то промежуточный слой-преобразователь.. но тут ещё не так принципиально..

2017-12-18 23:27 UTC, Bubliks commented
1

2017-12-19 08:14 UTC, leshiy1295 requested changes
Не до конца разделили интерфейс и модель на уровне инициализации карты, а также не все пути/константы вынесли в конфигурацию/в интерфейс.
Когда поправите - отпишитесь

2017-12-19 08:14 UTC, leshiy1295 commented on customsound.cpp
> +    setMedia(QUrl::fromLocalFile(QString::fromStdString(soundPath) + "menu/background.wav"));
это тоже должно быть в конфигурации

2017-12-19 08:14 UTC, leshiy1295 commented on main.cpp
> +    std::string filename =  "config.txt";
возможно, стоит брать это имя по умолчанию, но также проверить и argv

2017-12-19 08:14 UTC, leshiy1295 commented on mainwindow.cpp
> +    gameLoop = std::move(std::unique_ptr<QEventLoop>(new QEventLoop(ui->graphicsView)));
используйте make_unique

2017-12-19 08:14 UTC, leshiy1295 commented on mainwindow.h
> +    Ui::MainWindow *ui;
почему всё же Вы не используете умные указатели тут?

2017-12-19 08:14 UTC, leshiy1295 commented on mainwindow.cpp
> +void MainWindow::loadData(std::string map) {
это должна быть отдельная сущность...
У Вас сейчас MainWindow делает много чего - надо разнести по разным объектам

2017-12-19 08:14 UTC, leshiy1295 commented on mainwindow.cpp
> +    std::vector<std::string> map = {"1.txt"}; //this example
1.txt должен браться откуда-то?

2017-12-19 08:14 UTC, leshiy1295 commented on mainwindow.cpp
> +        loadData(map[i]);
у Вас сейчас интерфейсный класс отвечает за подгрузку моделей - это неправильно

2018-10-17 12:53 UTC, closed without merging